batch_size: 1
bvh_viz: false
data:
  clip_length: 128
  fps: 30
  gender: neutral
  normalize:
  - pos
  - velocity
  - global_xform
  - angular
  - height
  - root_orient
  - root_vel
  root_transform: true
  up: z
dataset_dir: ./data/amass/generative
dtw_loss: true
geodesic_loss: true
global_prior:
  activation: tanh
  in_channels: 6
  kernel_size: 4
  temporal_scale: 8
  z_dim: 256
initialization: true
is_train: false
keypoint_source: blend_std
l1_loss: true
lambda_angle: 1
lambda_dtw: 0.5
lambda_kl: 0.0001
local_prior:
  activation: tanh
  channel_base: 15
  extra_conv: 0
  kernel_size: 4
  num_layers: 4
  padding_mode: reflect
  skeleton_dist: 2
  skeleton_pool: mean
  temporal_scale: 8
  upsampling: linear
  use_residual_blocks: true
  z_dim: 1024
log: false
multi_gpu: false
nemf:
  bandwidth: 7
  global_output: 6
  global_z: 256
  hidden_neuron: 1024
  local_output: 144
  local_z: 1024
  norm_layer: true
  siren: false
  skip_connection: true
nsubject: 1
num_workers: 0
opt_betas: false
output_trans: false
overlap_len: 16
pretrained_gmp: false
save_dir: ./outputs/generative
scheduler:
  gamma: 0.7
  step_size: 200
stg1:
  betas_prior: 0
  keypoint_source: blend
  lambda_batch_cs: 0
  lambda_init_z_prior: 0
  lambda_j3d_smooth: 0
  lambda_motion_prior: 0
  lambda_orient: 0
  lambda_orient_smooth: 0
  lambda_pos: 0
  lambda_reproj: 0.05
  lambda_rot: 0
  lambda_rot_smooth: 0
  lambda_trans: 0
  lambda_trans_smooth: 0
  lr: 0.0
  niters: 0
  opt_params:
  - root_orient
stg2:
  betas_prior: 0
  lambda_batch_cs: 0
  lambda_init_z_prior: 0
  lambda_j3d_smooth: 0
  lambda_motion_prior: 0
  lambda_orient: 0
  lambda_orient_smooth: 0
  lambda_pos: 0
  lambda_reproj: 0
  lambda_rot: 0
  lambda_rot_smooth: 0
  lambda_trans: 0
  lambda_trans_smooth: 0
  lr: 0.0
  niters: 0
  opt_params:
  - trans
  - root_orient
stg3:
  betas_prior: 0
  lambda_batch_cs: 0
  lambda_init_z_prior: 0
  lambda_j3d_smooth: 0
  lambda_motion_prior: 0
  lambda_orient: 0
  lambda_orient_smooth: 0
  lambda_pos: 0
  lambda_reproj: 0
  lambda_rot: 0
  lambda_rot_smooth: 0
  lambda_trans: 0
  lambda_trans_smooth: 0
  lr: 0.0
  niters: 0
  opt_params:
  - root_orient
  - z_l
verbose: false
TRAIN:
  NUM_WORKERS: 8
  BATCH_SIZE: 64
  LOG_FERQ: 100
  SHUFFLE: True
  PIN_MEMORY: True
  USE_EFT: True
  USE_GT_CAM: False
  USE_ZERO_POSE: False
  HF_LOSS_ON: True
  BHF_MODE: 'full_body'
  FREEZE_ENCODER: ''
  FREEZE_PART: ''
  PW3D_RATIO: 0.2
  HR_IMG: False
  HF_ROOT_ALIGN: True
  USE_CONTOUR_2DLMK: True
TEST:
  BATCH_SIZE: 32
DATA:
  RESCALE_B: 1.
  RESCALE_H: 1.2
  RESCALE_F: 1.4
MODEL:
  # IWP, Identity rotation and Weak Perspective Camera
  USE_IWP_CAM: True
  USE_GT_FL: False
  PRED_PITCH: False
  MESH_MODEL: 'smplx'
  MESH_V2020: True
  N_BETAS_B: 10
  N_BETAS_H: 10
  N_BETAS_F: 100
  N_EXP: 50
  FACE_DENSE_SAM: True
  ADD_GENDER: False
  VPOSER_ON: False
  HAND_PCA_ON: False
  ALL_GENDER: False
  PyMAF:
    BACKBONE: 'hr48'
    HF_BACKBONE: 'res50'
    MAF_ON: True
    MLP_DIM: [256, 128, 64, 5]
    HF_MLP_DIM: [256, 128, 64, 5]
    MLP_VT_DIM: [256, 128, 64, 3]
    N_ITER: 3
    SUPV_LAST: False
    AUX_SUPV_ON: True
    HF_AUX_SUPV_ON: False
    HF_BOX_ALIGN: False
    DP_HEATMAP_SIZE: 56
    SEG_ON: False
    SEG_LAST: False
    GRID_FEAT: False
    USE_CAM_FEAT: True
    HF_IMG_SIZE: 224
    ADD_GRID: False
    OPT_WRIST: True     # correct wrist rotation
    ADAPT_INTEGR: True
    PRED_VIS_H: True
    HAND_VIS_TH: 0.1     # visible threshold for correcting wrist rotation
    OPT_HEAD: False      # correct head rotation
    HEAD_VIS_TH: 0.5     # visible threshold for correcting head rotation
    GRID_ALIGN:
      USE_ATT: True
      USE_FC: False
      ATT_FEAT_IDX: 2
      ATT_HEAD: 1
      ATT_STARTS: 1
POSE_RES_MODEL:
  INIT_WEIGHTS: True
  NAME: 'pose_resnet'
  PRETR_SET: 'imagenet'   # 'none' 'imagenet' 'coco'
  # PRETRAINED: 'data/pretrained_model/resnet50-19c8e357.pth'
  PRETRAINED_IM: 'data/pretrained_model/resnet50-19c8e357.pth'
  PRETRAINED_COCO: 'data/pretrained_model/pose_resnet_50_256x192.pth.tar'
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 48
    - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: False
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50